language: php

php:
    - 5.5
    - 7.1
    - hhvm
env:
  global:
    - TEST_COMMAND="vendor/bin/phpunit"
  matrix:
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_VERSION=2.7.* TEST_COMMAND="vendor/bin/phpunit --coverage-text --coverage-clover=build/coverage.xml"

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - $TEST_COMMAND